import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import config

def send_summary_emails(recipients, summary, meet_url):
    """Send meeting summary emails to all recipients."""
    try:
        server = smtplib.SMTP(config.EMAIL_HOST, config.EMAIL_PORT)
        server.starttls()
        server.login(config.EMAIL_HOST_USER, config.EMAIL_HOST_PASSWORD)
        formatted_summary = summary.replace('\n', '<br>')
        
        for recipient in recipients:
            msg = MIMEMultipart()
            msg['From'] = config.EMAIL_HOST_USER
            msg['To'] = recipient
            msg['Subject'] = f"Meeting Summary - Google Meet"
            body = f"""
            <html>
              <body>
                <h2>Meeting Summary</h2>
                <p><strong>Meeting Link:</strong> {meet_url}</p>
                <h3>Summary:</h3>
                <p>{formatted_summary}</p>
                <p>This summary was automatically generated by the Meeting Bot.</p>
              </body>
            </html>
            """
            
            msg.attach(MIMEText(body, 'html'))
            
            # Send email
            server.send_message(msg)
            print(f"Sent summary email to: {recipient}")
            
        server.quit()
        print("All summary emails sent successfully")
        
    except Exception as e:
        print(f"Error sending emails: {e}")
